= Access Your Lab Environment

During this lab you will be instructed to ssh to your hypervisor at IP address `{bastion_public_hostname}`.
Use username `{bastion_ssh_user_name}` and password `{bastion_ssh_password}`. The uuid of your lab is: `{guid}`


Once logged in the hypervisor you can access to the bastion at IP address `192.168.123.100` as `root` using password `redhat`.

If needed, you can navigate to the OpenShift console URL: {ocp_console_url}[{ocp_console_url}^] using user `admin` and password `{ocp_admin_password}`

== Prerequisites for Installation

Some prerequisites needed to install Red Hat OpenStack Services on OpenShift (RHOSO) are already included in the lab environment such as:

* An operational OpenShift cluster which supports Multus CNI
* oc command line tool on your workstation (bastion host)
* k9s command line tool on your workstation (bastion host)
* podman command line tool on your workstation (bastion host)
* Access to repositories which contain the Dev Preview code
* Access to an existing satellite. In this lab we will install a non-production oriented Red Hat satellite.
* Access to an existing registry or create a local Quay registry. In this lab we will install a non-production oriented of Quay.
* Example YAML files are available in this repository which can be cloned or copy and pasted for use.