= {lab_name}

Welcome to the Red Hat OpenStack Services on OpenShift (RHOSO) lab instructions.
These instructions will guide you through the installation of the next generation of Red Hat's OpenStack product onto an existing OpenShift Cluster utilizing a bastion host and a single host for the data plane.

In this lab, you will use the following infrastructure:

* A 3 node 4.14 OCP cluster
* A RHEL 9.3 bastion host dataplane

In this lab, you will cover the following topics:

* xref:prereqs.adoc[_Perform Pre-requisites_]
* xref:install-operators.adoc[_Install the Red Hat OpenStack Platform Service Operators_]
* xref:secure.adoc[_Configure Secure Access for OpenStack Services_]
* xref:network-isolation.adoc[_Prepare OCP for OpenStack Network Isolation_]
* xref:create-cp.adoc[_Create the Control Plane_]
* xref:create-dp.adoc[_Create the Data plane_]
* xref:access.adoc[_Access the Data Plane_]

Within the lab environment, you will be able to copy and paste the specified commands into the CLI.
For some steps you may also need to edit some of the commands from the  instructions.

*Be sure to review all commands carefully both for functionality and syntax!*

When you're ready, click "next" to get started...
