= {lab_name}

Welcome to the Red Hat OpenStack Services on OpenShift (RHOSO) lab instructions.
These instructions will guide you through the installation of the next generation of Red Hat's OpenStack product onto an existing OpenShift Cluster utilizing a bastion host and a single host for the data plane.

In this lab, you will use the following infrastructure:

* A 3 node 4.14 OCP cluster
* A RHEL 9.3 bastion host dataplane

In this lab, you will cover the following topics:

* xref:prereqs.adoc[Perform Prerequisite Operations]
* xref:install-operators.adoc[Install the Red Hat OpenStack Platform Service Operators]
* xref:secure.adoc[Configure Secure Access for OpenStack Services]
* xref:network-isolation.adoc[Prepare OCP for OpenStack Network Isolation]
* xref:create-cp.adoc[Create the Control Plane]
* xref:create-dp.adoc[Create the Data plane]
* xref:access.adoc[Access OpenStack]

Within the lab environment, you will be able to copy and paste the specified commands into the CLI.
For some steps you may also need to edit some of the commands from the  instructions.

*Be sure to review all commands carefully both for functionality and syntax!*

When you're ready, click "next" to get started...
