= Install the OpenStack Operator

== Clone the files repo

In the bastion terminal, clone the repo and change directory to the files that we will used later in the lab

[source,bash]
----
git clone https://github.com/pnavarro/showroom_osp-on-ocp-lb1374.git labrepo
cd labrepo/content/files
----

== Install the OpenStack Operators

The next step in installing the *OpenStack Operators* will be to login to the cluster using the _*oc_ command and _admin_ user utilizing the provided password for your lab.

#TODO export variables from lab

[source,bash]
----
oc login -u admin -p <password>
----

Create the *openstack-operators* project for the RHOSO operators:

[source,bash]
----
oc new-project openstack-operators
----

Create the `openstack` project for the deployed RHOSO environment:

[source,bash]
----
oc new-project openstack
----

=== Prepare the secret for installating the operators:

Login with your RedHat account and create a secret:

#TODO modify with the temporary registry.redhat.io user
[source,bash]
----
podman login registry.redhat.io 
podman login registry.redhat.io --authfile auth.json
----
Create secret for the registry: 
[source,bash]
----
oc create secret generic osp-operators-secret \
 -n openstack-operators \
 --from-file=.dockerconfigjson=auth.json \
 --type=kubernetes.io/dockerconfigjson
----

=== Configure the **Catalog Source, OperatorGroup and Subscription** for the **OpenStack Operator** using your registry: 

Create the new **CatalogSource, OperatorGroup, and Subscription** CRs in the **openstack** namespace from **files/openstack-operators.yaml**: You can cut and paste the referenced yamlfiles from the repo or you may wish to clone the repository onto the bastion which this guide will assume: 

[source,bash]
----
oc apply -f osp-ng-openstack-operator.yaml
----

Confirm that you have installed the Openstack Operator, **openstack-operator.openstack-operators**: ``` oc get operators openstack-operator.openstack-operators ``` 

Review the pods in the **openstack-operators** namespace: 
[source,bash]
----
oc get pods -n openstack-operators
----

#TODO Add checking operators

If you run:
[source, bash]
----
oc get pods -n openstack-operators --sort-by=.metadata.creationTimestamp
----

You should see a list of completed pods and then the running openstack services pods. It should looks like:
[source, bash]
----
(...)
4125610f4af9dfe5c6e5c6f7eee599a6b7a7211154c9c2a29bb1290239gq966   0/1     Completed   0          7m49s
c0899d48e01d3359dbcab05499bcee071d413f937e1f712d949751a098f844r   0/1     Completed   0          7m48s
2ce988007db74ed96e2b4f6223d3c76d9a6e177368efdc7c468b73a0bc4fk47   0/1     Completed   0          7m48s
neutron-operator-controller-manager-5755996c4b-ctbf8              2/2     Running     0          7m19s
openstack-ansibleee-operator-controller-manager-6d7d77fc45pdtfj   2/2     Running     0          7m13s
openstack-operator-controller-manager-56fb74ccb7-r8lvn            2/2     Running     0          7m1s
dataplane-operator-controller-manager-6844bfd645-f2zvs            2/2     Running     0          7m1s
glance-operator-controller-manager-596b56cd5-rvfrm                2/2     Running     0          6m59s
swift-operator-controller-manager-df5fbbbc5-zscc5                 2/2     Running     0          6m49s
octavia-operator-controller-manager-6549bc8f-r6xbp                2/2     Running     0          6m42s
openstack-baremetal-operator-controller-manager-7cd655c4c7f5glm   2/2     Running     0          6m42s
barbican-operator-controller-manager-69b766c996-ldg4n             2/2     Running     0          6m28s
(...)
----
