== Preparing RHOCP for RHOSP Network Isolation

We will be using a preconfigured set of yaml files in the `files` directory which start with `osp-ng-nncp-`.
There are 3 files for each of the control plane and worker nodes.

Change to the `files` directory:

[source,bash,role=execute]
----
cd ~/labrepo/content/files
----

Apply preconfigured yamls indivdually:

[source,bash,role=execute]
----
oc apply -f osp-ng-nncp-w1.yaml
oc apply -f osp-ng-nncp-w2.yaml
oc apply -f osp-ng-nncp-w3.yaml
----

Wait until they are in an available state before proceeding:

[source,bash,role=execute]
----
oc get nncp -w
----

.Sample Output
[source,bash]
----
NAME                              STATUS      REASON
osp-enp1s0-worker-ocp4-worker1    Available   SuccessfullyConfigured
osp-enp1s0-worker-ocp4-worker2    Available   SuccessfullyConfigured
osp-enp1s0-worker-ocp4-worker3    Available   SuccessfullyConfigured
----

Before proceeding configure a *nad* resource for each isolated network to attach a service pod to the network:

[source,bash,role=execute]
----
oc apply -f osp-ng-netattach.yaml
----

Once the nodes are available and attached configure the *MetalLB IP address range* using a preconfigured yaml file:

[source,bash,role=execute]
----
oc apply -f osp-ng-metal-lb-ip-address-pools.yaml
----

Lastly, configure a *L2Advertisement* resource which will define which node advertises a service to the local network which has been preconfigured for your demo environment:

[source,bash,role=execute]
----
oc apply -f osp-ng-metal-lb-l2-advertisements.yaml
----